/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as RealisatiesRouteImport } from './routes/realisaties'
import { Route as DienstenIndexRouteImport } from './routes/diensten.index'
import { Route as DienstenSlugRouteImport } from './routes/diensten.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisatiesRoute = RealisatiesRouteImport.update({
  id: '/realisaties',
  path: '/realisaties',
  getParentRoute: () => rootRouteImport,
} as any)
const DienstenIndexRoute = DienstenIndexRouteImport.update({
  id: '/diensten/',
  path: '/diensten/',
  getParentRoute: () => rootRouteImport,
} as any)
const DienstenSlugRoute = DienstenSlugRouteImport.update({
  id: '/diensten/$slug',
  path: '/diensten/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/over-ons': typeof OverOnsRoute
  '/realisaties': typeof RealisatiesRoute
  '/diensten/$slug': typeof DienstenSlugRoute
  '/diensten/': typeof DienstenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/over-ons': typeof OverOnsRoute
  '/realisaties': typeof RealisatiesRoute
  '/diensten/$slug': typeof DienstenSlugRoute
  '/diensten': typeof DienstenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/over-ons': typeof OverOnsRoute
  '/realisaties': typeof RealisatiesRoute
  '/diensten/$slug': typeof DienstenSlugRoute
  '/diensten/': typeof DienstenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/over-ons' | '/realisaties' | '/diensten/$slug' | '/diensten/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/over-ons' | '/realisaties' | '/diensten/$slug' | '/diensten'
  id:
    | '__root__'
    | '/'
    | '/over-ons'
    | '/realisaties'
    | '/diensten/$slug'
    | '/diensten/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OverOnsRoute: typeof OverOnsRoute
  RealisatiesRoute: typeof RealisatiesRoute
  DienstenSlugRoute: typeof DienstenSlugRoute
  DienstenIndexRoute: typeof DienstenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisaties': {
      id: '/realisaties'
      path: '/realisaties'
      fullPath: '/realisaties'
      preLoaderRoute: typeof RealisatiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diensten/': {
      id: '/diensten/'
      path: '/diensten'
      fullPath: '/diensten/'
      preLoaderRoute: typeof DienstenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diensten/$slug': {
      id: '/diensten/$slug'
      path: '/diensten/$slug'
      fullPath: '/diensten/$slug'
      preLoaderRoute: typeof DienstenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OverOnsRoute: OverOnsRoute,
  RealisatiesRoute: RealisatiesRoute,
  DienstenSlugRoute: DienstenSlugRoute,
  DienstenIndexRoute: DienstenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
